defaults: &defaults
  adapter: mongodb
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: youme_development

test:
  <<: *defaults
  database: youme_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: 
  port: 
  username: 
  password: 
  database: 